/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompetitionStatus from './CompetitionStatus';
import CompetitionType from './CompetitionType';
import ComplexFilter from './ComplexFilter';
import ProductReduced from './ProductReduced';

/**
 * The CompetitionReducedAllOf model module.
 * @module model/CompetitionReducedAllOf
 * @version 1.0.0
 */
class CompetitionReducedAllOf {
    /**
     * Constructs a new <code>CompetitionReducedAllOf</code>.
     * @alias module:model/CompetitionReducedAllOf
     * @param competitionType {module:model/CompetitionType} 
     * @param numberOfRounds {Number} Number of rounds to be played in a competition
     * @param name {String} A name or a name of a competition. Can be translated
     * @param optinRequiredForEntrants {Boolean} If True, members must Opt in before they can acquire points in the contest
     * @param status {module:model/CompetitionStatus} 
     * @param statusCode {Number} The code of the competition
     * @param products {Array.<module:model/ProductReduced>} 
     * @param scheduledStartDate {Date} ISO8601 timestamp for when a Competition should start. All records are stored in UTC time zone
     * @param scheduledEndDate {Date} ISO8601 timestamp for when a Competition should end. All records are stored in UTC time zone
     */
    constructor(competitionType, numberOfRounds, name, optinRequiredForEntrants, status, statusCode, products, scheduledStartDate, scheduledEndDate) { 
        
        CompetitionReducedAllOf.initialize(this, competitionType, numberOfRounds, name, optinRequiredForEntrants, status, statusCode, products, scheduledStartDate, scheduledEndDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, competitionType, numberOfRounds, name, optinRequiredForEntrants, status, statusCode, products, scheduledStartDate, scheduledEndDate) { 
        obj['competitionType'] = competitionType;
        obj['numberOfRounds'] = numberOfRounds;
        obj['name'] = name;
        obj['optinRequiredForEntrants'] = optinRequiredForEntrants;
        obj['status'] = status;
        obj['statusCode'] = statusCode;
        obj['products'] = products;
        obj['scheduledStartDate'] = scheduledStartDate;
        obj['scheduledEndDate'] = scheduledEndDate;
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['competitionType'];
        obj['numberOfRounds'];
        obj['name'];
        obj['includeEntrantsWhere'];
        obj['optinRequiredForEntrants'];
        obj['status'];
        obj['statusCode'];
        obj['products'];
        obj['scheduledStartDate'];
        obj['scheduledEndDate'];
        obj['actualStartDate'];
        obj['actualEndDate'];

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['competitionType'];
        obj["fields"]['numberOfRounds'];
        obj["fields"]['name'];
        obj["fields"]['includeEntrantsWhere'];
        obj["fields"]['optinRequiredForEntrants'];
        obj["fields"]['status'];
        obj["fields"]['statusCode'];
        obj["fields"]['products'];
        obj["fields"]['scheduledStartDate'];
        obj["fields"]['scheduledEndDate'];
        obj["fields"]['actualStartDate'];
        obj["fields"]['actualEndDate'];

        
        obj["requiredFields"]['competitionType'];
        obj["requiredFields"]['numberOfRounds'];
        obj["requiredFields"]['name'];
        obj["requiredFields"]['optinRequiredForEntrants'];
        obj["requiredFields"]['status'];
        obj["requiredFields"]['statusCode'];
        obj["requiredFields"]['products'];
        obj["requiredFields"]['scheduledStartDate'];
        obj["requiredFields"]['scheduledEndDate'];

        return obj;
    }

    /**
     * Constructs a <code>CompetitionReducedAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitionReducedAllOf} obj Optional instance to populate.
     * @return {module:model/CompetitionReducedAllOf} The populated <code>CompetitionReducedAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitionReducedAllOf();

            if (data.hasOwnProperty('competitionType')) {
                obj['competitionType'] = CompetitionType.constructFromObject(data['competitionType']);
            }
            if (data.hasOwnProperty('numberOfRounds')) {
                obj['numberOfRounds'] = ApiClient.convertToType(data['numberOfRounds'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('includeEntrantsWhere')) {
                obj['includeEntrantsWhere'] = ComplexFilter.constructFromObject(data['includeEntrantsWhere']);
            }
            if (data.hasOwnProperty('optinRequiredForEntrants')) {
                obj['optinRequiredForEntrants'] = ApiClient.convertToType(data['optinRequiredForEntrants'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = CompetitionStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [ProductReduced]);
            }
            if (data.hasOwnProperty('scheduledStartDate')) {
                obj['scheduledStartDate'] = ApiClient.convertToType(data['scheduledStartDate'], 'Date');
            }
            if (data.hasOwnProperty('scheduledEndDate')) {
                obj['scheduledEndDate'] = ApiClient.convertToType(data['scheduledEndDate'], 'Date');
            }
            if (data.hasOwnProperty('actualStartDate')) {
                obj['actualStartDate'] = ApiClient.convertToType(data['actualStartDate'], 'Date');
            }
            if (data.hasOwnProperty('actualEndDate')) {
                obj['actualEndDate'] = ApiClient.convertToType(data['actualEndDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CompetitionType} competitionType
 */
CompetitionReducedAllOf.prototype['competitionType'] = undefined;

/**
 * Number of rounds to be played in a competition
 * @member {Number} numberOfRounds
 */
CompetitionReducedAllOf.prototype['numberOfRounds'] = undefined;

/**
 * A name or a name of a competition. Can be translated
 * @member {String} name
 */
CompetitionReducedAllOf.prototype['name'] = undefined;

/**
 * @member {module:model/ComplexFilter} includeEntrantsWhere
 */
CompetitionReducedAllOf.prototype['includeEntrantsWhere'] = undefined;

/**
 * If True, members must Opt in before they can acquire points in the contest
 * @member {Boolean} optinRequiredForEntrants
 */
CompetitionReducedAllOf.prototype['optinRequiredForEntrants'] = undefined;

/**
 * @member {module:model/CompetitionStatus} status
 */
CompetitionReducedAllOf.prototype['status'] = undefined;

/**
 * The code of the competition
 * @member {Number} statusCode
 */
CompetitionReducedAllOf.prototype['statusCode'] = undefined;

/**
 * @member {Array.<module:model/ProductReduced>} products
 */
CompetitionReducedAllOf.prototype['products'] = undefined;

/**
 * ISO8601 timestamp for when a Competition should start. All records are stored in UTC time zone
 * @member {Date} scheduledStartDate
 */
CompetitionReducedAllOf.prototype['scheduledStartDate'] = undefined;

/**
 * ISO8601 timestamp for when a Competition should end. All records are stored in UTC time zone
 * @member {Date} scheduledEndDate
 */
CompetitionReducedAllOf.prototype['scheduledEndDate'] = undefined;

/**
 * ISO8601 timestamp for when a Competition started. All records are stored in UTC time zone
 * @member {Date} actualStartDate
 */
CompetitionReducedAllOf.prototype['actualStartDate'] = undefined;

/**
 * ISO8601 timestamp for when a Competition ended. All records are stored in UTC time zone
 * @member {Date} actualEndDate
 */
CompetitionReducedAllOf.prototype['actualEndDate'] = undefined;






export default CompetitionReducedAllOf;

