/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MemberType from './MemberType';
import Metadata from './Metadata';

/**
 * The CreateMemberRequest model module.
 * @module model/CreateMemberRequest
 * @version 1.0.4
 */
class CreateMemberRequest {
    /**
     * Constructs a new <code>CreateMemberRequest</code>.
     * @alias module:model/CreateMemberRequest
     * @param memberRefId {String} The reference to this member in your system
     * @param memberType {module:model/MemberType} 
     */
    constructor(memberRefId, memberType) { 
        
        CreateMemberRequest.initialize(this, memberRefId, memberType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, memberRefId, memberType) { 
        obj['memberRefId'] = memberRefId;
        obj['memberType'] = memberType;
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['name'];
        obj['memberRefId'];
        obj['memberType'];
        obj['groups'];
        obj['metadata'];

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['name'];
        obj["fields"]['memberRefId'];
        obj["fields"]['memberType'];
        obj["fields"]['groups'];
        obj["fields"]['metadata'];

        
        obj["requiredFields"]['memberRefId'];
        obj["requiredFields"]['memberType'];

        return obj;
    }

    /**
     * Constructs a <code>CreateMemberRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateMemberRequest} obj Optional instance to populate.
     * @return {module:model/CreateMemberRequest} The populated <code>CreateMemberRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateMemberRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('memberRefId')) {
                obj['memberRefId'] = ApiClient.convertToType(data['memberRefId'], 'String');
            }
            if (data.hasOwnProperty('memberType')) {
                obj['memberType'] = MemberType.constructFromObject(data['memberType']);
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['String']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [Metadata]);
            }
        }
        return obj;
    }


}

/**
 * The name of the member that is used on leader boards and public displays
 * @member {String} name
 */
CreateMemberRequest.prototype['name'] = undefined;

/**
 * The reference to this member in your system
 * @member {String} memberRefId
 */
CreateMemberRequest.prototype['memberRefId'] = undefined;

/**
 * @member {module:model/MemberType} memberType
 */
CreateMemberRequest.prototype['memberType'] = undefined;

/**
 * A list of Strings of groups that the member belongs to. It could be marketing segments or social friend groups
 * @member {Array.<String>} groups
 */
CreateMemberRequest.prototype['groups'] = undefined;

/**
 * @member {Array.<module:model/Metadata>} metadata
 */
CreateMemberRequest.prototype['metadata'] = undefined;






export default CreateMemberRequest;

