/**
 * CompetitionLabs Application Services
 * CompetitionLabs Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EventRefType.
* @enum {}
* @readonly
*/
export default class EventRefType {
    
        /**
         * value: "CompetitionType"
         * @const
         */
        "CompetitionType" = "CompetitionType";

    
        /**
         * value: "ContestType"
         * @const
         */
        "ContestType" = "ContestType";

    
        /**
         * value: "AchievementType"
         * @const
         */
        "AchievementType" = "AchievementType";

    
        /**
         * value: "UserTypeType"
         * @const
         */
        "UserTypeType" = "UserTypeType";

    
        /**
         * value: "MemberMessageType"
         * @const
         */
        "MemberMessageType" = "MemberMessageType";

    

    /**
    * Returns a <code>EventRefType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EventRefType} The enum <code>EventRefType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

