/**
 * CompetitionLabs Application Services
 * CompetitionLabs Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Connection from './Connection';
import CustomFieldReduced from './CustomFieldReduced';
import KafkaConnectionAllOf from './KafkaConnectionAllOf';
import Metadata from './Metadata';
import ModelDefault from './ModelDefault';
import OptParamModels from './OptParamModels';
import TagsReduced from './TagsReduced';

/**
 * The KafkaConnection model module.
 * @module model/KafkaConnection
 * @version 1.0.0
 */
class KafkaConnection {
    /**
     * Constructs a new <code>KafkaConnection</code>.
     * @alias module:model/KafkaConnection
     * @extends module:model/Connection
     * @implements module:model/Connection
     * @implements module:model/ModelDefault
     * @implements module:model/OptParamModels
     * @implements module:model/KafkaConnectionAllOf
     * @param id {String} A unique system generated identifier
     * @param spaceName {String} This is the space name which is linked to the account
     * @param created {Date} ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
     * @param objectType {String} The type of consumer to create
     * @param name {String} The name of the consumer
     * @param brokers {Array.<String>} Kafka broker endpoints.
     * @param groupId {String} Group Id for connection
     * @param topic {String} Topic name
     * @param lastKnownStatus {String} Last known status of the connection
     * @param lastKnownStatusCode {Number} Status code correspoding to the last known status
     * @param transformerId {String} The identifier of the transformer
     */
    constructor(id, spaceName, created, objectType, name, brokers, groupId, topic, lastKnownStatus, lastKnownStatusCode, transformerId) { 
        Connection.initialize(this, id, spaceName, created, objectType);ModelDefault.initialize(this, id, spaceName, created);OptParamModels.initialize(this);KafkaConnectionAllOf.initialize(this, name, brokers, groupId, topic, lastKnownStatus, lastKnownStatusCode, transformerId);
        KafkaConnection.initialize(this, id, spaceName, created, objectType, name, brokers, groupId, topic, lastKnownStatus, lastKnownStatusCode, transformerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, spaceName, created, objectType, name, brokers, groupId, topic, lastKnownStatus, lastKnownStatusCode, transformerId) { 
        obj['id'] = id;
        obj['spaceName'] = spaceName;
        obj['created'] = created;
        obj['name'] = name;
        obj['brokers'] = brokers;
        obj['groupId'] = groupId;
        obj['topic'] = topic;
        obj['lastKnownStatus'] = lastKnownStatus;
        obj['lastKnownStatusCode'] = lastKnownStatusCode;
        obj['transformerId'] = transformerId;
    }

    /**
     * Constructs a <code>KafkaConnection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KafkaConnection} obj Optional instance to populate.
     * @return {module:model/KafkaConnection} The populated <code>KafkaConnection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KafkaConnection();
            Connection.constructFromObject(data, obj);
            Connection.constructFromObject(data, obj);
            ModelDefault.constructFromObject(data, obj);
            OptParamModels.constructFromObject(data, obj);
            KafkaConnectionAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('spaceName')) {
                obj['spaceName'] = ApiClient.convertToType(data['spaceName'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [CustomFieldReduced]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagsReduced]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [Metadata]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('brokers')) {
                obj['brokers'] = ApiClient.convertToType(data['brokers'], ['String']);
            }
            if (data.hasOwnProperty('groupId')) {
                obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('lastKnownStatus')) {
                obj['lastKnownStatus'] = ApiClient.convertToType(data['lastKnownStatus'], 'String');
            }
            if (data.hasOwnProperty('lastKnownStatusCode')) {
                obj['lastKnownStatusCode'] = ApiClient.convertToType(data['lastKnownStatusCode'], 'Number');
            }
            if (data.hasOwnProperty('transformerId')) {
                obj['transformerId'] = ApiClient.convertToType(data['transformerId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A unique system generated identifier
 * @member {String} id
 */
KafkaConnection.prototype['id'] = undefined;

/**
 * This is the space name which is linked to the account
 * @member {String} spaceName
 */
KafkaConnection.prototype['spaceName'] = undefined;

/**
 * ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
 * @member {Date} created
 */
KafkaConnection.prototype['created'] = undefined;

/**
 * @member {Array.<module:model/CustomFieldReduced>} customFields
 */
KafkaConnection.prototype['customFields'] = undefined;

/**
 * A list of id's used to tag models
 * @member {Array.<module:model/TagsReduced>} tags
 */
KafkaConnection.prototype['tags'] = undefined;

/**
 * @member {Array.<module:model/Metadata>} metadata
 */
KafkaConnection.prototype['metadata'] = undefined;

/**
 * The name of the consumer
 * @member {String} name
 */
KafkaConnection.prototype['name'] = undefined;

/**
 * Kafka broker endpoints.
 * @member {Array.<String>} brokers
 */
KafkaConnection.prototype['brokers'] = undefined;

/**
 * Group Id for connection
 * @member {String} groupId
 */
KafkaConnection.prototype['groupId'] = undefined;

/**
 * Topic name
 * @member {String} topic
 */
KafkaConnection.prototype['topic'] = undefined;

/**
 * Last known status of the connection
 * @member {String} lastKnownStatus
 */
KafkaConnection.prototype['lastKnownStatus'] = undefined;

/**
 * Status code correspoding to the last known status
 * @member {Number} lastKnownStatusCode
 */
KafkaConnection.prototype['lastKnownStatusCode'] = undefined;

/**
 * The identifier of the transformer
 * @member {String} transformerId
 */
KafkaConnection.prototype['transformerId'] = undefined;


// Implement Connection interface:
/**
 * A unique system generated identifier
 * @member {String} id
 */
Connection.prototype['id'] = undefined;
/**
 * This is the space name which is linked to the account
 * @member {String} spaceName
 */
Connection.prototype['spaceName'] = undefined;
/**
 * ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
 * @member {Date} created
 */
Connection.prototype['created'] = undefined;
/**
 * The type of consumer to create
 * @member {String} objectType
 */
Connection.prototype['objectType'] = undefined;
// Implement ModelDefault interface:
/**
 * A unique system generated identifier
 * @member {String} id
 */
ModelDefault.prototype['id'] = undefined;
/**
 * This is the space name which is linked to the account
 * @member {String} spaceName
 */
ModelDefault.prototype['spaceName'] = undefined;
/**
 * ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
 * @member {Date} created
 */
ModelDefault.prototype['created'] = undefined;
// Implement OptParamModels interface:
/**
 * @member {Array.<module:model/CustomFieldReduced>} customFields
 */
OptParamModels.prototype['customFields'] = undefined;
/**
 * A list of id's used to tag models
 * @member {Array.<module:model/TagsReduced>} tags
 */
OptParamModels.prototype['tags'] = undefined;
/**
 * @member {Array.<module:model/Metadata>} metadata
 */
OptParamModels.prototype['metadata'] = undefined;
// Implement KafkaConnectionAllOf interface:
/**
 * The name of the consumer
 * @member {String} name
 */
KafkaConnectionAllOf.prototype['name'] = undefined;
/**
 * Kafka broker endpoints.
 * @member {Array.<String>} brokers
 */
KafkaConnectionAllOf.prototype['brokers'] = undefined;
/**
 * Group Id for connection
 * @member {String} groupId
 */
KafkaConnectionAllOf.prototype['groupId'] = undefined;
/**
 * Topic name
 * @member {String} topic
 */
KafkaConnectionAllOf.prototype['topic'] = undefined;
/**
 * Last known status of the connection
 * @member {String} lastKnownStatus
 */
KafkaConnectionAllOf.prototype['lastKnownStatus'] = undefined;
/**
 * Status code correspoding to the last known status
 * @member {Number} lastKnownStatusCode
 */
KafkaConnectionAllOf.prototype['lastKnownStatusCode'] = undefined;
/**
 * The identifier of the transformer
 * @member {String} transformerId
 */
KafkaConnectionAllOf.prototype['transformerId'] = undefined;




export default KafkaConnection;

