/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollaboratorAllOf from './CollaboratorAllOf';
import ModelDefault from './ModelDefault';

/**
 * The Collaborator model module.
 * @module model/Collaborator
 * @version 1.0.0
 */
class Collaborator {
    /**
     * Constructs a new <code>Collaborator</code>.
     * @alias module:model/Collaborator
     * @implements module:model/ModelDefault
     * @implements module:model/CollaboratorAllOf
     * @param id {String} A unique system generated identifier
     * @param spaceName {String} This is the space name which is linked to the account
     * @param created {Date} ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
     * @param email {String} The email of the user to log in
     * @param role {String} The access role of an individual
     */
    constructor(id, spaceName, created, email, role) { 
        ModelDefault.initialize(this, id, spaceName, created);CollaboratorAllOf.initialize(this, email, role);
        Collaborator.initialize(this, id, spaceName, created, email, role);
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['id'] = null;
        obj['spaceName'] = null;
        obj['created'] = null;
        obj['name'] = null;
        obj['surname'] = null;
        obj['email'] = null;
        obj['role'] = null;

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['id'] = { "type": 'String' };
        obj["fields"]['spaceName'] = { "type": 'String' };
        obj["fields"]['created'] = { "type": 'Date' };
        obj["fields"]['name'] = { "type": 'String' };
        obj["fields"]['surname'] = { "type": 'String' };
        obj["fields"]['email'] = { "type": 'String' };
        obj["fields"]['role'] = { "type": 'String' };

        
        obj["requiredFields"]['id'] = { "type": 'String' };
        obj["requiredFields"]['spaceName'] = { "type": 'String' };
        obj["requiredFields"]['created'] = { "type": 'Date' };
        obj["requiredFields"]['email'] = { "type": 'String' };
        obj["requiredFields"]['role'] = { "type": 'String' };

        return obj;
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, spaceName, created, email, role) { 
        obj['id'] = id;
        obj['spaceName'] = spaceName;
        obj['created'] = created;
        obj['email'] = email;
        obj['role'] = role;
    }

    /**
     * Constructs a <code>Collaborator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Collaborator} obj Optional instance to populate.
     * @return {module:model/Collaborator} The populated <code>Collaborator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Collaborator();
            ModelDefault.constructFromObject(data, obj);
            CollaboratorAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('spaceName')) {
                obj['spaceName'] = ApiClient.convertToType(data['spaceName'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A unique system generated identifier
 * @member {String} id
 */
Collaborator.prototype['id'] = undefined;

/**
 * This is the space name which is linked to the account
 * @member {String} spaceName
 */
Collaborator.prototype['spaceName'] = undefined;

/**
 * ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
 * @member {Date} created
 */
Collaborator.prototype['created'] = undefined;

/**
 * The Name of an individual
 * @member {String} name
 */
Collaborator.prototype['name'] = undefined;

/**
 * The Surname of an individual
 * @member {String} surname
 */
Collaborator.prototype['surname'] = undefined;

/**
 * The email of the user to log in
 * @member {String} email
 */
Collaborator.prototype['email'] = undefined;

/**
 * The access role of an individual
 * @member {String} role
 */
Collaborator.prototype['role'] = undefined;


// Implement ModelDefault interface:
/**
 * A unique system generated identifier
 * @member {String} id
 */
ModelDefault.prototype['id'] = undefined;
/**
 * This is the space name which is linked to the account
 * @member {String} spaceName
 */
ModelDefault.prototype['spaceName'] = undefined;
/**
 * ISO8601 timestamp for when a Model was created. All records are stored in UTC time zone
 * @member {Date} created
 */
ModelDefault.prototype['created'] = undefined;
// Implement CollaboratorAllOf interface:
/**
 * The Name of an individual
 * @member {String} name
 */
CollaboratorAllOf.prototype['name'] = undefined;
/**
 * The Surname of an individual
 * @member {String} surname
 */
CollaboratorAllOf.prototype['surname'] = undefined;
/**
 * The email of the user to log in
 * @member {String} email
 */
CollaboratorAllOf.prototype['email'] = undefined;
/**
 * The access role of an individual
 * @member {String} role
 */
CollaboratorAllOf.prototype['role'] = undefined;




export default Collaborator;

