/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AchievementLiveStatus from './AchievementLiveStatus';
import CreateRewardRequest from './CreateRewardRequest';
import DependantOn from './DependantOn';
import Metadata from './Metadata';
import RuleSet from './RuleSet';
import Scheduling from './Scheduling';
import Translation from './Translation';

/**
 * The CreateAchievementRequest model module.
 * @module model/CreateAchievementRequest
 * @version 1.0.1
 */
class CreateAchievementRequest {
    /**
     * Constructs a new <code>CreateAchievementRequest</code>.
     * @alias module:model/CreateAchievementRequest
     * @param name {String} A name for the Achievement. Can be translated
     * @param isHidden {Boolean} Informs the state of the achievement. True means hidden and false means revealed
     * @param icon {String} An Icon id that has been pre uploaded to the system to display for Achievement
     * @param ruleSets {Array.<module:model/RuleSet>} 
     * @param scheduling {module:model/Scheduling} 
     * @param achievementLiveStatus {module:model/AchievementLiveStatus} 
     */
    constructor(name, isHidden, icon, ruleSets, scheduling, achievementLiveStatus) { 
        
        CreateAchievementRequest.initialize(this, name, isHidden, icon, ruleSets, scheduling, achievementLiveStatus);
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['name'] = null;
        obj['description'] = null;
        obj['isHidden'] = null;
        obj['icon'] = null;
        obj['ruleSets'] = [new RuleSet().model()];
        obj['dependantOn'] = new DependantOn().model();
        obj['scheduling'] = new Scheduling().model();
        obj['achievementLiveStatus'] = new AchievementLiveStatus().model();
        obj['category'] = [null];
        obj['memberGroups'] = [null];
        obj['metadata'] = [new Metadata().model()];
        obj['translations'] = [new Translation().model()];
        obj['rewards'] = [new CreateRewardRequest().model()];
        obj['constraints'] = [null];

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['name'] = { "type": 'String', "system": false };
        obj["fields"]['description'] = { "type": 'String', "system": false };
        obj["fields"]['isHidden'] = { "type": 'Boolean', "system": false };
        obj["fields"]['icon'] = { "type": 'String', "system": false };
        obj["fields"]['ruleSets'] = [new RuleSet().modelMap()];
        obj["fields"]['dependantOn'] = new DependantOn().modelMap();
        obj["fields"]['scheduling'] = new Scheduling().modelMap();
        obj["fields"]['achievementLiveStatus'] = new AchievementLiveStatus().modelMap();
        obj["fields"]['category'] = [{ "type": 'String', "system": false }];
        obj["fields"]['memberGroups'] = [{ "type": 'String', "system": false }];
        obj["fields"]['metadata'] = [new Metadata().modelMap()];
        obj["fields"]['translations'] = [new Translation().modelMap()];
        obj["fields"]['rewards'] = [new CreateRewardRequest().modelMap()];
        obj["fields"]['constraints'] = [{ "type": 'String', "system": false }];

        
        obj["requiredFields"]['name'] = { "type": 'String', "system": false };
        obj["requiredFields"]['isHidden'] = { "type": 'Boolean', "system": false };
        obj["requiredFields"]['icon'] = { "type": 'String', "system": false };
        obj["requiredFields"]['ruleSets'] = [new RuleSet().modelMap()];
        obj["requiredFields"]['scheduling'] = new Scheduling().modelMap();
        obj["requiredFields"]['achievementLiveStatus'] = new AchievementLiveStatus().modelMap();

        return obj;
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, isHidden, icon, ruleSets, scheduling, achievementLiveStatus) { 
        obj['name'] = name;
        obj['isHidden'] = isHidden;
        obj['icon'] = icon;
        obj['ruleSets'] = ruleSets;
        obj['scheduling'] = scheduling;
        obj['achievementLiveStatus'] = achievementLiveStatus;
    }

    /**
     * Constructs a <code>CreateAchievementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAchievementRequest} obj Optional instance to populate.
     * @return {module:model/CreateAchievementRequest} The populated <code>CreateAchievementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAchievementRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isHidden')) {
                obj['isHidden'] = ApiClient.convertToType(data['isHidden'], 'Boolean');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('ruleSets')) {
                obj['ruleSets'] = ApiClient.convertToType(data['ruleSets'], [RuleSet]);
            }
            if (data.hasOwnProperty('dependantOn')) {
                obj['dependantOn'] = DependantOn.constructFromObject(data['dependantOn']);
            }
            if (data.hasOwnProperty('scheduling')) {
                obj['scheduling'] = Scheduling.constructFromObject(data['scheduling']);
            }
            if (data.hasOwnProperty('achievementLiveStatus')) {
                obj['achievementLiveStatus'] = AchievementLiveStatus.constructFromObject(data['achievementLiveStatus']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], ['String']);
            }
            if (data.hasOwnProperty('memberGroups')) {
                obj['memberGroups'] = ApiClient.convertToType(data['memberGroups'], ['String']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [Metadata]);
            }
            if (data.hasOwnProperty('translations')) {
                obj['translations'] = ApiClient.convertToType(data['translations'], [Translation]);
            }
            if (data.hasOwnProperty('rewards')) {
                obj['rewards'] = ApiClient.convertToType(data['rewards'], [CreateRewardRequest]);
            }
            if (data.hasOwnProperty('constraints')) {
                obj['constraints'] = ApiClient.convertToType(data['constraints'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * A name for the Achievement. Can be translated
 * @member {String} name
 */
CreateAchievementRequest.prototype['name'] = undefined;

/**
 * A name for the Achievement. Can be translated
 * @member {String} description
 */
CreateAchievementRequest.prototype['description'] = undefined;

/**
 * Informs the state of the achievement. True means hidden and false means revealed
 * @member {Boolean} isHidden
 * @default false
 */
CreateAchievementRequest.prototype['isHidden'] = false;

/**
 * An Icon id that has been pre uploaded to the system to display for Achievement
 * @member {String} icon
 */
CreateAchievementRequest.prototype['icon'] = undefined;

/**
 * @member {Array.<module:model/RuleSet>} ruleSets
 */
CreateAchievementRequest.prototype['ruleSets'] = undefined;

/**
 * @member {module:model/DependantOn} dependantOn
 */
CreateAchievementRequest.prototype['dependantOn'] = undefined;

/**
 * @member {module:model/Scheduling} scheduling
 */
CreateAchievementRequest.prototype['scheduling'] = undefined;

/**
 * @member {module:model/AchievementLiveStatus} achievementLiveStatus
 */
CreateAchievementRequest.prototype['achievementLiveStatus'] = undefined;

/**
 * Categorisation of the achievements
 * @member {Array.<String>} category
 */
CreateAchievementRequest.prototype['category'] = undefined;

/**
 * A group of members that can receive the achievement
 * @member {Array.<String>} memberGroups
 */
CreateAchievementRequest.prototype['memberGroups'] = undefined;

/**
 * @member {Array.<module:model/Metadata>} metadata
 */
CreateAchievementRequest.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/Translation>} translations
 */
CreateAchievementRequest.prototype['translations'] = undefined;

/**
 * @member {Array.<module:model/CreateRewardRequest>} rewards
 */
CreateAchievementRequest.prototype['rewards'] = undefined;

/**
 * Additional constraints
 * @member {Array.<String>} constraints
 */
CreateAchievementRequest.prototype['constraints'] = undefined;






export default CreateAchievementRequest;

