/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityType from './EntityType';

/**
 * The MemberAwardAllOf model module.
 * @module model/MemberAwardAllOf
 * @version 1.0.1
 */
class MemberAwardAllOf {
    /**
     * Constructs a new <code>MemberAwardAllOf</code>.
     * @alias module:model/MemberAwardAllOf
     * @param rewardId {String} A unique identifier of a Reward
     * @param rewardTypeKey {String} The type of the Reward
     * @param rewardTypeId {String} A unique id of the Reward Type
     * @param rewardValue {Number} Numerical value of the reward that will be issued based on the reward type
     * @param claimed {Boolean} has the award been claimed or not
     * @param entityType {module:model/EntityType} 
     * @param entityId {String} The Id of the contest or achievement related to this Award. Dependant on entityType
     */
    constructor(rewardId, rewardTypeKey, rewardTypeId, rewardValue, claimed, entityType, entityId) { 
        
        MemberAwardAllOf.initialize(this, rewardId, rewardTypeKey, rewardTypeId, rewardValue, claimed, entityType, entityId);
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['rewardId'] = null;
        obj['rewardTypeKey'] = null;
        obj['rewardTypeId'] = null;
        obj['rewardValue'] = null;
        obj['memberAcknowledgmentRequired'] = null;
        obj['claimed'] = null;
        obj['delay'] = null;
        obj['entityType'] = new EntityType().model();
        obj['entityId'] = null;
        obj['pointInTime'] = null;
        obj['period'] = null;

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['rewardId'] = { "type": 'String' };
        obj["fields"]['rewardTypeKey'] = { "type": 'String' };
        obj["fields"]['rewardTypeId'] = { "type": 'String' };
        obj["fields"]['rewardValue'] = { "type": 'Number' };
        obj["fields"]['memberAcknowledgmentRequired'] = { "type": 'Boolean' };
        obj["fields"]['claimed'] = { "type": 'Boolean' };
        obj["fields"]['delay'] = { "type": 'Number' };
        obj["fields"]['entityType'] = new EntityType().modelMap();
        obj["fields"]['entityId'] = { "type": 'String' };
        obj["fields"]['pointInTime'] = { "type": 'Date' };
        obj["fields"]['period'] = { "type": 'Number' };

        
        obj["requiredFields"]['rewardId'] = { "type": 'String' };
        obj["requiredFields"]['rewardTypeKey'] = { "type": 'String' };
        obj["requiredFields"]['rewardTypeId'] = { "type": 'String' };
        obj["requiredFields"]['rewardValue'] = { "type": 'Number' };
        obj["requiredFields"]['claimed'] = { "type": 'Boolean' };
        obj["requiredFields"]['entityType'] = new EntityType().modelMap();
        obj["requiredFields"]['entityId'] = { "type": 'String' };

        return obj;
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rewardId, rewardTypeKey, rewardTypeId, rewardValue, claimed, entityType, entityId) { 
        obj['rewardId'] = rewardId;
        obj['rewardTypeKey'] = rewardTypeKey;
        obj['rewardTypeId'] = rewardTypeId;
        obj['rewardValue'] = rewardValue;
        obj['claimed'] = claimed;
        obj['entityType'] = entityType;
        obj['entityId'] = entityId;
    }

    /**
     * Constructs a <code>MemberAwardAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberAwardAllOf} obj Optional instance to populate.
     * @return {module:model/MemberAwardAllOf} The populated <code>MemberAwardAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberAwardAllOf();

            if (data.hasOwnProperty('rewardId')) {
                obj['rewardId'] = ApiClient.convertToType(data['rewardId'], 'String');
            }
            if (data.hasOwnProperty('rewardTypeKey')) {
                obj['rewardTypeKey'] = ApiClient.convertToType(data['rewardTypeKey'], 'String');
            }
            if (data.hasOwnProperty('rewardTypeId')) {
                obj['rewardTypeId'] = ApiClient.convertToType(data['rewardTypeId'], 'String');
            }
            if (data.hasOwnProperty('rewardValue')) {
                obj['rewardValue'] = ApiClient.convertToType(data['rewardValue'], 'Number');
            }
            if (data.hasOwnProperty('memberAcknowledgmentRequired')) {
                obj['memberAcknowledgmentRequired'] = ApiClient.convertToType(data['memberAcknowledgmentRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('claimed')) {
                obj['claimed'] = ApiClient.convertToType(data['claimed'], 'Boolean');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
            if (data.hasOwnProperty('entityId')) {
                obj['entityId'] = ApiClient.convertToType(data['entityId'], 'String');
            }
            if (data.hasOwnProperty('pointInTime')) {
                obj['pointInTime'] = ApiClient.convertToType(data['pointInTime'], 'Date');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * A unique identifier of a Reward
 * @member {String} rewardId
 */
MemberAwardAllOf.prototype['rewardId'] = undefined;

/**
 * The type of the Reward
 * @member {String} rewardTypeKey
 */
MemberAwardAllOf.prototype['rewardTypeKey'] = undefined;

/**
 * A unique id of the Reward Type
 * @member {String} rewardTypeId
 */
MemberAwardAllOf.prototype['rewardTypeId'] = undefined;

/**
 * Numerical value of the reward that will be issued based on the reward type
 * @member {Number} rewardValue
 */
MemberAwardAllOf.prototype['rewardValue'] = undefined;

/**
 * Requires member acknowledgment to claim a reward. If set to True reward will not be automatically issued
 * @member {Boolean} memberAcknowledgmentRequired
 * @default false
 */
MemberAwardAllOf.prototype['memberAcknowledgmentRequired'] = false;

/**
 * has the award been claimed or not
 * @member {Boolean} claimed
 */
MemberAwardAllOf.prototype['claimed'] = undefined;

/**
 * Delay of issuing a reward in minutes
 * @member {Number} delay
 * @default 0
 */
MemberAwardAllOf.prototype['delay'] = 0;

/**
 * @member {module:model/EntityType} entityType
 */
MemberAwardAllOf.prototype['entityType'] = undefined;

/**
 * The Id of the contest or achievement related to this Award. Dependant on entityType
 * @member {String} entityId
 */
MemberAwardAllOf.prototype['entityId'] = undefined;

/**
 * ISO8601 timestamp for when an Award is available until a specific point in time. All records are stored in UTC time zone. * There can only be one time definition used for claim period either \"pointInTime\" or \"period\"
 * @member {Date} pointInTime
 */
MemberAwardAllOf.prototype['pointInTime'] = undefined;

/**
 * Claimable duration in minutes, this value will set the controls until when the award is claimable. * There can only be one time definition used for claim period either \"pointInTime\" or \"period\"
 * @member {Number} period
 * @default 0
 */
MemberAwardAllOf.prototype['period'] = 0;






export default MemberAwardAllOf;

