/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UnitOfMeasureType.
* @enum {}
* @readonly
*/
export default class UnitOfMeasureType {
    
        /**
         * value: "Other"
         * @const
         */
        "Other" = "Other";

    
        /**
         * value: "Currency"
         * @const
         */
        "Currency" = "Currency";

    
        /**
         * value: "Mass"
         * @const
         */
        "Mass" = "Mass";

    
        /**
         * value: "Time"
         * @const
         */
        "Time" = "Time";

    
        /**
         * value: "Temperature"
         * @const
         */
        "Temperature" = "Temperature";

    
        /**
         * value: "ElectricCurrent"
         * @const
         */
        "ElectricCurrent" = "ElectricCurrent";

    
        /**
         * value: "AmountOfSubstance"
         * @const
         */
        "AmountOfSubstance" = "AmountOfSubstance";

    
        /**
         * value: "LuminousIntensity"
         * @const
         */
        "LuminousIntensity" = "LuminousIntensity";

    
        /**
         * value: "Distance"
         * @const
         */
        "Distance" = "Distance";

    

    /**
    * Constructs a full object with all available fields.
    */
    list(){
        var obj = {};

        
        obj['Other'] = "Other";
        
        obj['Currency'] = "Currency";
        
        obj['Mass'] = "Mass";
        
        obj['Time'] = "Time";
        
        obj['Temperature'] = "Temperature";
        
        obj['ElectricCurrent'] = "ElectricCurrent";
        
        obj['AmountOfSubstance'] = "AmountOfSubstance";
        
        obj['LuminousIntensity'] = "LuminousIntensity";
        
        obj['Distance'] = "Distance";
        

        return obj;
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        
        obj['Other'] = null;
        
        obj['Currency'] = null;
        
        obj['Mass'] = null;
        
        obj['Time'] = null;
        
        obj['Temperature'] = null;
        
        obj['ElectricCurrent'] = null;
        
        obj['AmountOfSubstance'] = null;
        
        obj['LuminousIntensity'] = null;
        
        obj['Distance'] = null;
        

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        return {"type": 'String'};
    }

    /**
    * Returns a <code>UnitOfMeasureType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UnitOfMeasureType} The enum <code>UnitOfMeasureType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

