/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateConnectionRequestAllOf from './UpdateConnectionRequestAllOf';
import UpdateModelDefault from './UpdateModelDefault';

/**
 * The UpdateConnectionRequest model module.
 * @module model/UpdateConnectionRequest
 * @version 1.0.1
 */
class UpdateConnectionRequest {
    /**
     * Constructs a new <code>UpdateConnectionRequest</code>.
     * @alias module:model/UpdateConnectionRequest
     * @implements module:model/UpdateModelDefault
     * @implements module:model/UpdateConnectionRequestAllOf
     * @param id {String} A unique system generated identifier
     * @param objectType {String} The type of consumer to create
     */
    constructor(id, objectType) { 
        UpdateModelDefault.initialize(this, id);UpdateConnectionRequestAllOf.initialize(this, objectType, id);
        UpdateConnectionRequest.initialize(this, id, objectType);
    }

    /**
    * Constructs a full object with all available fields.
    */
    model(){
        var obj = {};

        obj['id'] = null;
        obj['objectType'] = null;

        return obj;
    }

    /**
    * Constructs a full object Map for all available fields.
    */
    modelMap(){
        var obj = {
            "fields": {},
            "requiredFields": {}
        };

        obj["fields"]['id'] = { "type": 'String' };
        obj["fields"]['objectType'] = { "type": 'String' };

        
        obj["requiredFields"]['id'] = { "type": 'String' };
        obj["requiredFields"]['objectType'] = { "type": 'String' };

        return obj;
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, objectType) { 
        obj['id'] = id;
        obj['objectType'] = objectType;
    }

    /**
     * Constructs a <code>UpdateConnectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateConnectionRequest} obj Optional instance to populate.
     * @return {module:model/UpdateConnectionRequest} The populated <code>UpdateConnectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateConnectionRequest();
            UpdateModelDefault.constructFromObject(data, obj);
            UpdateConnectionRequestAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('objectType')) {
                obj['objectType'] = ApiClient.convertToType(data['objectType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A unique system generated identifier
 * @member {String} id
 */
UpdateConnectionRequest.prototype['id'] = undefined;

/**
 * The type of consumer to create
 * @member {String} objectType
 */
UpdateConnectionRequest.prototype['objectType'] = undefined;


// Implement UpdateModelDefault interface:
/**
 * A unique system generated identifier
 * @member {String} id
 */
UpdateModelDefault.prototype['id'] = undefined;
// Implement UpdateConnectionRequestAllOf interface:
/**
 * The type of consumer to create
 * @member {String} objectType
 */
UpdateConnectionRequestAllOf.prototype['objectType'] = undefined;
/**
 * A unique system generated identifier
 * @member {String} id
 */
UpdateConnectionRequestAllOf.prototype['id'] = undefined;




export default UpdateConnectionRequest;

