/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@CompetitionlabsInsightsServicesSdk);
  }
}(this, function(expect, @CompetitionlabsInsightsServicesSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateEventRequest', function() {
    it('should create an instance of CreateEventRequest', function() {
      // uncomment below and update the code to test CreateEventRequest
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be.a(@CompetitionlabsInsightsServicesSdk.CreateEventRequest);
    });

    it('should have the property memberRefId (base name: "memberRefId")', function() {
      // uncomment below and update the code to test the property memberRefId
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property batchId (base name: "batchId")', function() {
      // uncomment below and update the code to test the property batchId
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property entityRefId (base name: "entityRefId")', function() {
      // uncomment below and update the code to test the property entityRefId
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property sourceValue (base name: "sourceValue")', function() {
      // uncomment below and update the code to test the property sourceValue
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property transactionTimestamp (base name: "transactionTimestamp")', function() {
      // uncomment below and update the code to test the property transactionTimestamp
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new @CompetitionlabsInsightsServicesSdk.CreateEventRequest();
      //expect(instance).to.be();
    });

  });

}));
