/**
 * CompetitionLabs Application Services
 * The services listed below are referred as CompetitionLabs Application Services.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@CompetitionlabsJavascriptSdk);
  }
}(this, function(expect, @CompetitionlabsJavascriptSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @CompetitionlabsJavascriptSdk.QueryRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryRequest', function() {
    it('should create an instance of QueryRequest', function() {
      // uncomment below and update the code to test QueryRequest
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be.a(@CompetitionlabsJavascriptSdk.QueryRequest);
    });

    it('should have the property must (base name: "must")', function() {
      // uncomment below and update the code to test the property must
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property mustNot (base name: "mustNot")', function() {
      // uncomment below and update the code to test the property mustNot
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property should (base name: "should")', function() {
      // uncomment below and update the code to test the property should
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property gte (base name: "gte")', function() {
      // uncomment below and update the code to test the property gte
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property lte (base name: "lte")', function() {
      // uncomment below and update the code to test the property lte
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property gt (base name: "gt")', function() {
      // uncomment below and update the code to test the property gt
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property lt (base name: "lt")', function() {
      // uncomment below and update the code to test the property lt
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property range (base name: "range")', function() {
      // uncomment below and update the code to test the property range
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property sortBy (base name: "sortBy")', function() {
      // uncomment below and update the code to test the property sortBy
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property multiFields (base name: "multiFields")', function() {
      // uncomment below and update the code to test the property multiFields
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeFields (base name: "includeFields")', function() {
      // uncomment below and update the code to test the property includeFields
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property hasValue (base name: "hasValue")', function() {
      // uncomment below and update the code to test the property hasValue
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property hasNoValue (base name: "hasNoValue")', function() {
      // uncomment below and update the code to test the property hasNoValue
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property shouldMatch (base name: "shouldMatch")', function() {
      // uncomment below and update the code to test the property shouldMatch
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property skip (base name: "skip")', function() {
      // uncomment below and update the code to test the property skip
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property limit (base name: "limit")', function() {
      // uncomment below and update the code to test the property limit
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

    it('should have the property isCountQuery (base name: "isCountQuery")', function() {
      // uncomment below and update the code to test the property isCountQuery
      //var instane = new @CompetitionlabsJavascriptSdk.QueryRequest();
      //expect(instance).to.be();
    });

  });

}));
