/**
 * CompetitionLabs Admin Services
 * CompetitionLabs Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CompetitionLabsAdminServices);
  }
}(this, function(expect, CompetitionLabsAdminServices) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CompetitionLabsAdminServices.RepositoriesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RepositoriesApi', function() {
    describe('createFileObjectRepository', function() {
      it('should call createFileObjectRepository successfully', function(done) {
        //uncomment below and update the code to test createFileObjectRepository
        //instance.createFileObjectRepository(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFileObjectRepositoriesByQuery', function() {
      it('should call deleteFileObjectRepositoriesByQuery successfully', function(done) {
        //uncomment below and update the code to test deleteFileObjectRepositoriesByQuery
        //instance.deleteFileObjectRepositoriesByQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFileObjectRepositoryById', function() {
      it('should call deleteFileObjectRepositoryById successfully', function(done) {
        //uncomment below and update the code to test deleteFileObjectRepositoryById
        //instance.deleteFileObjectRepositoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFileObjectRepositoriesByQuery', function() {
      it('should call getFileObjectRepositoriesByQuery successfully', function(done) {
        //uncomment below and update the code to test getFileObjectRepositoriesByQuery
        //instance.getFileObjectRepositoriesByQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getListOfFileObjectRepositories', function() {
      it('should call getListOfFileObjectRepositories successfully', function(done) {
        //uncomment below and update the code to test getListOfFileObjectRepositories
        //instance.getListOfFileObjectRepositories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFileObjectRepository', function() {
      it('should call updateFileObjectRepository successfully', function(done) {
        //uncomment below and update the code to test updateFileObjectRepository
        //instance.updateFileObjectRepository(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
